steps:
  # Step 1: Clone the Git repository into a subdirectory
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/pybase-net/python-tools.git', '/workspace/repo']

  # Step 2: Build the Docker image from the cloned repository
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/python-tools:latest',
      '.'
    ]
    dir: '/workspace/repo'

  # Step 3: Push the Docker image with the commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/python-tools:latest'
    ]

  # Step 4: Push the Docker image with the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/python-tools:latest'
    ]

  # Step 5: Optionally, deploy the image to Cloud Run or another service
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: [
#      'run', 'deploy', 'python-tools-service',
#      '--image', 'gcr.io/$PROJECT_ID/python-tools:latest',
#      '--platform', 'managed',
#      '--region', 'us-central1',
#      '--vpc-connector', 'my-vpc-connector',  # If you have a VPC connector
#      '--allow-unauthenticated'
#    ]

images:
  - 'gcr.io/$PROJECT_ID/python-tools:latest'
