steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      "build",
      "-t", "gcr.io/${PROJECT_ID}/redis-celery-image:latest",
      '.'
    ]

  # Step 2: Push the Docker image with the commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/redis-celery-image:latest'
    ]

  # Step 3: Push the Docker image with the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/redis-celery-image:latest'
    ]

  # Step 4: Optionally, deploy the image to Cloud Run or another service
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: [
#      'run', 'deploy', 'redis-celery-service',
#      '--image', 'gcr.io/$PROJECT_ID/redis-celery-image:latest',
#      '--platform', 'managed',
#      '--region', 'us-central1',
#      '--allow-unauthenticated'
#    ]

images:
  - 'gcr.io/$PROJECT_ID/redis-celery-image:latest'
