version: "3.4"

services:
  celery:
    container_name: my_celery
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  redis:
    image: redis:7.0.11-alpine3.18
    container_name: my_redis
    restart: no
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
      - redis_data:/data
networks:
  python_tools:
volumes:
  redis_data: {}